package dev.syncforge.ksp

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSFile

class SyncForgeProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor =
        SyncForgeProcessor(environment.codeGenerator, environment.logger)
}

private data class EntityCodegenInfo(
    val entityName: String,
    val packageName: String,
    val entityType: String,
    val qualifiedEntity: String,
    val daoName: String,
    val daoPackage: String,
    val handlerName: String,
    val daoParamName: String,
    val sourceFiles: List<KSFile>,
)

class SyncForgeProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
) : SymbolProcessor {

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val entityAnnotation = "dev.syncforge.annotations.SyncForgeEntity"
        val daoAnnotation = "dev.syncforge.annotations.SyncForgeDao"

        val entities = resolver.getSymbolsWithAnnotation(entityAnnotation)
            .filterIsInstance<KSClassDeclaration>()
            .sortedBy { it.qualifiedName?.asString().orEmpty() }
            .toList()

        if (entities.isEmpty()) return emptyList()

        val daos = resolver.getSymbolsWithAnnotation(daoAnnotation)
            .filterIsInstance<KSClassDeclaration>()
            .associateBy { dao ->
                dao.annotations.first { it.shortName.getShortName() == "SyncForgeDao" }
                    .arguments.first().value as String
            }

        val codegenInfos = mutableListOf<EntityCodegenInfo>()

        entities.forEach { entity ->
            val entityName = entity.simpleName.asString()
            val packageName = entity.packageName.asString()
            val entityType = entity.annotations.first {
                it.shortName.getShortName() == "SyncForgeEntity"
            }.arguments.first().value as String
            val qualifiedEntity = "$packageName.$entityName"

            val dao = daos[qualifiedEntity]
            if (dao == null) {
                logger.error("No @SyncForgeDao found for $qualifiedEntity", entity)
                return@forEach
            }

            val daoName = dao.simpleName.asString()
            val daoPackage = dao.packageName.asString()
            val handlerName = "${entityName}SyncHandler"
            val sourceFiles = listOfNotNull(entity.containingFile, dao.containingFile)
            val daoParamName = entityName.removeSuffix("Entity")
                .replaceFirstChar { if (it.isUpperCase()) it.lowercase() else it.toString() } + "Dao"

            val info = EntityCodegenInfo(
                entityName = entityName,
                packageName = packageName,
                entityType = entityType,
                qualifiedEntity = qualifiedEntity,
                daoName = daoName,
                daoPackage = daoPackage,
                handlerName = handlerName,
                daoParamName = daoParamName,
                sourceFiles = sourceFiles,
            )
            codegenInfos += info
            generateHandler(info)
        }

        if (codegenInfos.isNotEmpty()) {
            generateHandlersRegistry(codegenInfos)
        }

        return emptyList()
    }

    private fun generateHandler(info: EntityCodegenInfo) {
        codeGenerator.createNewFile(
            dependencies = Dependencies(false, *info.sourceFiles.toTypedArray()),
            packageName = info.packageName,
            fileName = info.handlerName,
        ).use { stream ->
            stream.write(
                """
                package ${info.packageName}

                import dev.syncforge.entity.TypedEntitySyncHandler
                import dev.syncforge.model.SyncState
                import kotlinx.serialization.json.Json
                import kotlinx.serialization.encodeToString
                import kotlinx.serialization.decodeFromString

                /**
                 * Auto-generated by SyncForge KSP — do not edit manually.
                 */
                class ${info.handlerName}(
                    private val dao: ${info.daoPackage}.${info.daoName},
                    private val json: Json = Json { ignoreUnknownKeys = true },
                ) : TypedEntitySyncHandler<${info.entityName}>() {

                    override val entityType: String = "${info.entityType}"

                    override fun toJson(entity: ${info.entityName}): String = json.encodeToString(entity)

                    override fun fromJson(jsonString: String): ${info.entityName} = json.decodeFromString(jsonString)

                    override suspend fun findById(id: String): ${info.entityName}? = dao.findById(id)

                    override suspend fun insert(entity: ${info.entityName}) { dao.insert(entity) }

                    override suspend fun update(entity: ${info.entityName}) { dao.update(entity) }

                    override suspend fun deleteById(id: String) { dao.deleteById(id) }

                    override fun withSyncState(entity: ${info.entityName}, state: SyncState): ${info.entityName} =
                        entity.copy(syncState = state)
                }
                """.trimIndent().toByteArray(),
            )
        }
    }

    private fun generateHandlersRegistry(infos: List<EntityCodegenInfo>) {
        val packageName = infos.first().packageName
        val allSourceFiles = infos.flatMap { it.sourceFiles }.distinct().toTypedArray()

        val factoryFunctions = infos.joinToString(separator = "\n\n    ") { info ->
            """
            fun ${info.entityType}(${info.daoParamName}: ${info.daoPackage}.${info.daoName}): ${info.handlerName} =
                ${info.handlerName}(${info.daoParamName})
            """.trimIndent()
        }

        val registryParams = infos.joinToString(separator = ",\n        ") { info ->
            "${info.daoParamName}: ${info.daoPackage}.${info.daoName}"
        }
        val registryHandlers = infos.joinToString(separator = ", ") { info ->
            "${info.entityType}(${info.daoParamName})"
        }
        val handlerImports = infos
            .distinctBy { it.packageName to it.handlerName }
            .joinToString(separator = "\n") { info ->
                "import ${info.packageName}.${info.handlerName}"
            }

        codeGenerator.createNewFile(
            dependencies = Dependencies(false, *allSourceFiles),
            packageName = packageName,
            fileName = "SyncForgeHandlers",
        ).use { stream ->
            stream.write(
                """
                package $packageName

                import dev.syncforge.entity.EntityRegistry
                $handlerImports

                /**
                 * Auto-generated by SyncForge KSP — wires all @SyncForgeEntity handlers for this module.
                 */
                object SyncForgeHandlers {

                    $factoryFunctions

                    fun registry(
                        $registryParams,
                    ): EntityRegistry = EntityRegistry.of($registryHandlers)
                }
                """.trimIndent().toByteArray(),
            )
        }
    }
}