tasks.register("linkIosFrameworksForXcode") {
    group = "build"
    description =
        "Builds Kotlin frameworks for the active Xcode SDK and writes Configuration/GeneratedFrameworks.xcconfig."

    doLast {
        val srcRoot = System.getenv("SRCROOT")
            ?: (findProperty("xcodeSrcRoot") as String?)
            ?: error("SRCROOT (or -PxcodeSrcRoot) is required")
        val platformName = System.getenv("PLATFORM_NAME") ?: "iphonesimulator"
        val repoRoot = file(srcRoot).parentFile

        val (target, frameworkFolder) = when (platformName) {
            "iphonesimulator" -> {
                if (System.getProperty("os.arch") == "aarch64") {
                    "IosSimulatorArm64" to "iosSimulatorArm64"
                } else {
                    "IosX64" to "iosX64"
                }
            }
            else -> "IosArm64" to "iosArm64"
        }

        logger.lifecycle("Building Kotlin frameworks for $target ($frameworkFolder)...")
        exec {
            workingDir = repoRoot
            commandLine(
                repoRoot.resolve("gradlew").absolutePath,
                ":syncforge:linkDebugFramework$target",
                ":sample-ios-shared:linkDebugFramework$target",
            )
        }

        val generated = file("$srcRoot/Configuration/GeneratedFrameworks.xcconfig")
        generated.parentFile.mkdirs()
        generated.writeText(
            """
            // Generated by linkIosFrameworksForXcode — do not edit.
            REPO_ROOT = ${repoRoot.absolutePath}
            SYNCFORGE_FRAMEWORK_DIR = ${'$'}(REPO_ROOT)/syncforge/build/bin/$frameworkFolder/debugFramework
            SAMPLE_FRAMEWORK_DIR = ${'$'}(REPO_ROOT)/sample-ios-shared/build/bin/$frameworkFolder/debugFramework
            FRAMEWORK_SEARCH_PATHS = ${'$'}(inherited) ${'$'}(SYNCFORGE_FRAMEWORK_DIR) ${'$'}(SAMPLE_FRAMEWORK_DIR)
            """.trimIndent() + "\n",
        )
        logger.lifecycle("Wrote ${generated.absolutePath}")
    }
}