#!/usr/bin/env bash
# Builds Kotlin/Native frameworks for the active Xcode SDK.
set -euo pipefail

REPO_ROOT="$(cd "${SRCROOT}/.." && pwd)"
cd "${REPO_ROOT}"

GRADLE="${REPO_ROOT}/gradlew"
if [[ ! -x "${GRADLE}" ]]; then
  echo "error: gradlew not found at ${GRADLE}" >&2
  exit 1
fi

if [[ "${PLATFORM_NAME:-}" == "iphonesimulator" ]]; then
  if [[ "$(uname -m)" == "arm64" ]]; then
    TARGET="IosSimulatorArm64"
  else
    TARGET="IosX64"
  fi
else
  TARGET="IosArm64"
fi

case "${TARGET}" in
  IosSimulatorArm64) FRAMEWORK_FOLDER="iosSimulatorArm64" ;;
  IosX64) FRAMEWORK_FOLDER="iosX64" ;;
  IosArm64) FRAMEWORK_FOLDER="iosArm64" ;;
  *)
    echo "error: unsupported Kotlin target ${TARGET}" >&2
    exit 1
    ;;
esac

echo "Building Kotlin frameworks for ${TARGET} (${FRAMEWORK_FOLDER})..."
"${GRADLE}" \
  ":syncforge:linkDebugFramework${TARGET}" \
  ":sample-ios-shared:linkDebugFramework${TARGET}"

GENERATED_XCCONFIG="${SRCROOT}/Configuration/GeneratedFrameworks.xcconfig"
cat > "${GENERATED_XCCONFIG}" <<EOF
// Generated by build-kotlin-frameworks.sh — do not edit.
REPO_ROOT = ${REPO_ROOT}
SYNCFORGE_FRAMEWORK_DIR = \$(REPO_ROOT)/syncforge/build/bin/${FRAMEWORK_FOLDER}/debugFramework
SAMPLE_FRAMEWORK_DIR = \$(REPO_ROOT)/sample-ios-shared/build/bin/${FRAMEWORK_FOLDER}/debugFramework
FRAMEWORK_SEARCH_PATHS = \$(inherited) \$(SYNCFORGE_FRAMEWORK_DIR) \$(SAMPLE_FRAMEWORK_DIR)
EOF

echo "Wrote ${GENERATED_XCCONFIG}"